name: pull-request

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0
      -   name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      -   name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: gsdevmebot
            password: ${{ secrets.DOCKER_HUB }}
      -   name: Build
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: gsdevme/solismon3:${{ github.event.pull_request.head.sha }}