name: push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0
      -   name: Create Git Semver Tag
          run: npx semantic-release --branches master -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github
