name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
          with:
            fetch-depth: 0
      -   name: Get Semver tag
          id: git
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -   name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      -   name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: gsdevmebot
            password: ${{ secrets.DOCKER_HUB }}
      -   name: Build
          id: docker_push
          uses: docker/build-push-action@v2
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: gsdevme/solismon3:latest, gsdevme/solismon3:${{ steps.git.outputs.tag }}